[project]
name = "anki-doc-master"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.2"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.129.0",
    "uvicorn>=0.41.0",
]
